### ISSUE TITLE
Implement prod_flag variable read schema - applicable to small number of data products

### ISSUE THREAD

**Issue by ngachung** [nasa-jpl/mango-ingest#35]
For ACC1A (and at least some other datasets), there is a `prod_flag` column, which holds an array of binary flags indicating whether a given field/column is present in the record.

Until now, we've assumed that this will be constant for a given dataset.

We need to follow up with the science team to check whether this assumption is valid (and whether this column needs to be stored in the database).

If it's not valid, the input file schema is actually non-static, and we'll need to design/implement a parser to deal with that.

@ngachung @mike-gangl 

I'll drop a message in teams shortly, but don't want to forget

Clone of https://github.jpl.nasa.gov/Mass-Change/gmat-ingest/issues/42

**Comment by ngachung** [comment]
@IrinaTkatcheva has encountered a file with varying `prod_flag` - `AHK1A_2023-06-01_C_04.txt`

```
738849600  107733  R  C  00000000   00111100000000000000010001000000  9.984976053237915 0.001019239426 0 0 0  00000000000000000000000000000000
738849600  207726  R  C  00000000   00111100000000000000000001000100  26.0137372493744 9.98498797416687 0 0 0  00000000000000000000000000000000
738849600  307720  R  C  00000000   00111100000000000000000001000100  26.01418428421022 9.984993934631348 0 0 0  00000000000000000000000000000000
738849600  407713  R  C  00000000   00111100000010000000000001000000  9.984993934631348 4.946689129 0 0 0  00000000000000000000000000000000
```

```
- prod_flag:
        bit_masks: !<!> "[1b, 2b, 4b, 8b, 16b, 32b, 64b, 128b, 256b, 512b, 1024b, 2048b, 4096b, 8192b, 16384b, 32768b, 65536b, 131072b, 262144b, 524288b, 1048576b, 2097152b, 4194304b, 8388608b, 1677216b, 33554432b, 67108864b, 134217728b, 268435456b, 536870912b]"
        bit_meanings:
          - bit 0 = TFEEU_IF
          - bit 1 = TFEEU_REF
          - bit 2 = TFEEU_X
          - bit 3 = TFEEU_YZ
          - bit 4 = analog_GND
          - bit 5 = +3.3V
          - bit 6 = Vp
          - bit 7 = MES_Vd
          - bit 8 = MES_DET_X1
          - bit 9 = MES_DET_X2
          - bit 10 = MES_DET_X3
          - bit 11 = MES_DET_Y1
          - bit 12 = MES_DET_Y2
          - bit 13 = MES_DET_Z1
          - bit 14 = TSU_Y+
          - bit 15 = TICUN
          - bit 16 = TSU_Y-
          - bit 17 = TSU_Z+
          - bit 18 = TSU_Z-
          - bit 19 = +5V
          - bit 20 = TICUR
          - bit 21 = +15V
          - bit 22 = -15V
          - bit 23 = +48V
          - bit 24 = -48V
          - bit 25 = Not defined
          - bit 26 = ICU block number
          - bit 27 = PPS Source
          - bit 28 = Sync Quality Index
          - bit 29 = Status flag
          - bits 30-31 = Not defined
        comment: 6th column
        coverage_content_type: referenceInformation
        long_name: Product flag, if bit set to 1, value is present in record, bit 0 is rightmost
    - TFEEU_IF:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TFEEU_REF:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TFEEU_X:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TFEEU_YZ:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - analog_GND:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - +3.3V:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - Vp:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - MES_Vd:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - MES_DET_X1:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - MES_DET_X2:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - MES_DET_X3:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - MES_DET_Y1:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - MES_DET_Y2:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - MES_DET_Z1:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TSU_Y+:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TICUN:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TSU_Y-:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TSU_Z+:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TSU Z-:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - +5V:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - TICUR:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - +15V:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - -15V:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - +48V:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - -48V:
        comment: next column, if prod_flag bit set
        coverage_content_type: physicalMeasurement
    - status:
        comment: next column, if prod_flag bit set
        long_name: Not defined for GRACE-FO
    - icu_blk_nr:
        comment: next column, if prod_flag bit set
        coverage_content_type: referenceInformation
        long_name: ICU block number. Assigned with the millisecond of the day of the timestamp for GRACE-FO.
    - PPS_source:
        comment: next column, if prod_flag bit set
        coverage_content_type: referenceInformation
        long_name: PPS source
        valid_range: 0, 5
        value_meanings:
          - 0 - IN SYNC WITH GPS
          - 1 - OUT OF SYNC
          - 2 - SYNC IN PROGRESS BAD PPS
          - 3 - SYNC IN PROGRESS GOOD PPS
          - 4 - SYNC TO GROUND UTC IN PROGRESS
          - 5 - IN SYNC WITH GROUND UTC
    - Sync_Qual:
        comment: next column, if prod_flag bit set
        coverage_content_type: qualityInformation
        long_name: Sync Quality Index
        valid_range: 0, 3
        value_meanings:
          - 0 - PPS RECEIVED TIME PACKET RECEIVED
          - 1 - PPS NOT RECEIVED TIME PACKET RECEIVED
          - 2 - PPS RECEIVED TIME PACKET NOT RECEIVED
          - 3 - PPS NOT RECEIVED TIME PACKET NOT RECEIVED
    - statusflag:
        bit_masks: !<!> "[1b, 2b, 4b, 8b, 16b, 32b, 64b, 128b, 256b, 512b, 1024b, 2048b, 4096b, 8192b, 16384b, 32768b, 65536b, 131072b, 262144b]"
        bit_meanings:
          - bit 0 = Test registers. 0 - Test ADC registers function is enabled, 1 - Test ADC registers function is disabled
          - bit 1 = Status, Vp. 0 - Vp 10V, 1 - Vp 40V
          - bit 2 = Status, Vd. 0 - Vd 5Vrms, 1 - Vp 1.25Vrms
          - bit 3 = Flag, SCI_ACC_X. 0 - ADC is synchronised, 1 - Time-out is detected
          - bit 4 = Flag, SCI_ACC_Y
          - bit 5 = Flag, SCI_ACC_Z
          - bit 6 = Flag, SCI_ACC_Phi
          - bit 7 = Flag, SCI_ACC_Theta
          - bit 8 = Flag, SCI_ACC_Psi
          - bit 9 = Flag, SCI_VP
          - bit 10 = Flag, SCI_MUX1
          - bit 11 = Flag, SCI_MUX2
          - bit 12 = Flag, SCI_MUX3
          - bit 13 = Flag, test registers. Shows when the ADC registers check has proceeded. 0 - ADC bit registers are NOT tested, 1 - ADC registers are tested
          - bit 14 = Flag, validity of registers. 0 - All the ADC registers are identical to the initial value, 1 - At least one of the ADC registers is corrupt
          - bit 15 = GWT. 0 - The stops are connected, 1 - The stops are NOT connected
          - bit 16 = Event Report Generation. 0 - Event Report Generation function is disabled, 1 - Event Report Generation function is enabled
          - bit 17 = PPS Channel. 0 - PPS A, 1 - PPS B
          - bit 18 = Uart Channel. 0 - Uart A, 1 - Uart B
          - bits 19-31 = Not defined
        comment: next column, if prod_flag bit set
        coverage_content_type: qualityInformation
        long_name: Status flag
```
